### PR TITLE
First stab at AboutPage

### LINKED ISSUE #7: Fill in the about page
Just ordinary markdown as in https://github.com/JuliaAI/MLJ/blob/main/src/data/AboutPage.md
CC @ablaom

### PR DESCRIPTION
**Pull request by ablaom**
Closes #7.

@EssamWisam I'm not too clear on how to mix markdown and html in a way that my previewer will understand, but  think my intentions are clear.

### CODE REVIEW

**Comment by EssamWisam** [comment]
I did some modifications for spacing (and a minor formatting modification). What do you think? Feel free to revert any change.

**Comment by ablaom** [comment]
Thanks!

I'd say the gaps between paragraphs is still too large:

Screen Shot 2024-07-23 at 10 40 22 AM

**Comment by EssamWisam** [comment]
> Thanks!
> 
> I'd say the gaps between paragraphs is still too large:

Should be fixed now: use `<br><br>` in a new line when you want white space. Modern web frameworks usually have powerful markdown plugins that are much smarter than this but the particular framework I'm  using is a little new in the area.

**Comment by ablaom** [comment]
Happy enough with this now.

**Comment by EssamWisam** [comment]
@ablaom Feel free to merge then.

**Pull request merged**
