### PR TITLE
Add tags and one package

### PR DESCRIPTION
**Pull request by ablaom**

### CODE REVIEW

**Comment by EssamWisam** [comment]
Thank you @ablaom for these changes. For the models page:

image

image

I have a feeling that we lost symmetry in the two buttons after renaming them (i.e., they are no longer of the same width). It just crossed my mind that I can actually force the width to be equal as an attempt to force them to be equal but it may be slightly better if the text itself ensures that.

Now with the original marketing headline gone: 
- Do you think the search placeholder would benefit from mentioning the number of models? 
- What do you think about completely removing the headline? (navigation bar exposes that this is the models page already)
- Did you intentionally leave the marketing headline in the tutorials page untouched?
- What about showing the marketing headlines only under a low probability (e.g., 20%) else hide them?

**Comment by ablaom** [comment]
> I have a feeling that we lost symmetry in the two buttons after renaming them 

Sorry, I'm going to push back on this. [Form follows function](https://en.wikipedia.org/wiki/Form_follows_function#:~:text=Form%20follows%20function%20is%20a,its%20intended%20function%20or%20purpose). :wink:

I've moved MetaAlgoriths to "approach" and renamed distrubution fitters, as discussed offline.

As you know I'm conservative about marketing. I think that this should be avoided in pages like "models" and "tutorials" which I think speak for themselves. Naturally, we want to sell the ecosystem features on the landing page. 

So instead, I've now added for the top of "Models" and "Tutorials" rotating suggestions on models or tutorials to try. What do you think?

**Comment by ablaom** [comment]
I see that the preview now fails on the Tutorials page, but that is also happening on `main`.

**Comment by EssamWisam** [comment]
> Sorry, I'm going to push back on this. Form follows function

Rational I didn't know and I agree now that I can just deal with it in the styles.

> I've moved MetaAlgoriths to "approach" and renamed distrubution fitters, as discussed offline.

Great.

> As you know I'm conservative about marketing. I think that this should be avoided in pages like "models" and "tutorials" which I think speak for themselves. Naturally, we want to sell the ecosystem features on the landing page.

Again, rational logic that I do agree with. Perhaps I felt the gap because we didn't start with the homepage.

> So instead, I've now added for the top of "Models" and "Tutorials" rotating suggestions on models or tutorials to try. What do you think?

Love the idea of the rotating suggestions but I think that headline is too much for them. I will make another smaller headline (in font size/boldness) to appear below the search bar to rotate these suggestion and deprecate that main headline. What do you think?

**Comment by ablaom** [comment]
> Love the idea of the rotating suggestions but I think that headline is too much for them. I will make another smaller headline (in font size/boldness) to appear below the search bar to rotate these suggestion and deprecate that main headline. What do you think?

Yes, you read my thoughts.

**Comment by EssamWisam** [comment]
@ablaom need to change "feature selection" into "feature engineering" in the yaml of the tutorials page as well.

**Comment by ablaom** [comment]
> need to change "feature selection" into "feature engineering" in the yaml of the tutorials page as well.
 
done.

**Comment by EssamWisam** [comment]
@ablaom Not sure if you have changed `Dimensionality Reduction` into `Dimension Reduction` in the host repo but that was another issue with the model's page preventing the list from being shown. So I will change it here to "Dimension Reduction".

**Comment by ablaom** [comment]
Thanks for the fixes. Let me know if I've missing anything else. I didn't add "Meta Algorithms" to the tutorial tags, because I don't think we tagged any tutorials with that.

Otherwise, I don't have anything to add at this point. Later, when after your planned enhancement, I can update the  suggestions with live links.

**Comment by EssamWisam** [comment]
@ablaom just one thing missing that I have just added:

I have deprecated the headlines and added rotating suggestions feature for tutorials page and models pages (while adding the missing links). I further made them rotate every 7 seconds or as otherwise specified in the corresponding yaml.

For the model's page, every refresh triggers a new suggestion (as well every t seconds). Meanwhile, for the tutorials page I made the default hint be `Looking for a sequential progression of tutorials? See
   [DataScienceTutorials.jl](https://juliaai.github.io/DataScienceTutorials.jl/)` after 7 seconds or so pass it rotates to the others because that suggestion is the most important.

**Comment by EssamWisam** [comment]
I lastly changed the neural network image as I wasn't feeling so good with the existing one and made a minor style improvement. Merging this.

**Pull request merged**
